<?php
define ( 'PROJECT_MODULE', 'CGV_VALIDACION' );
define ( 'PROJECT_TITLE', 'Hash Coder' );
define ( 'PROJECT_SHORT_TITLE', 'HashCoder' );
define ( 'PROJECT_PREFIX', 'HC' );

define ( 'ERROR_CODE_LOGIN', 'bG9naW4gZXJyb3I=' );
define ( 'ERROR_MSG_LOGIN', '¡VERIFICA TU CAPTURA!' );
define ( 'ERROR_CODE_BLOCKED', 'bG9naW4gYmxvY2tlZA==' );
define ( 'ERROR_MSG_BLOCKED', 'LO SENTIMOS, SU CUENTA HA SIDO BLOQUEADA, FAVOR DE CONTACTAR AL ADMINISTRADOR DEL SISTEMA' );
?>